### ISSUE TITLE
Crashes on geometry columns

### ISSUE THREAD

**Issue by xalikoutis** [kenjiuno/EdmGen06#2]
EdmGen06 Information: 101 :  Parameter: geom1

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at EdmGen06.EdmGenModelGen.ModelGen2(String connectionString, String provider
Name, String typeProviderServices, String modelName, String targetSchema, Versio
n yver) in c:\Proj\EdmGen06\EdmGenModelGen.cs:line 451
   at EdmGen06.EdmGenModelGen.ModelGen(String connectionString, String providerN
ame, String modelName, String targetSchema, Version yver) in c:\Proj\EdmGen06\Ed
mGenModelGen.cs:line 23
   at EdmGen06.Program.Main(String[] args) in c:\Proj\EdmGen06\Program.cs:line 9

Is it possible to just ignore it?

**Comment by kenjiuno** [comment]
Hi.
Thank you for reporting the problem!
I will check it about your issue.

**Comment by kenjiuno** [comment]
Ok, please try newer one: _EdmGen06_20140605.7z_

https://github.com/kenjiuno/EdmGen06/releases/tag/0.7.0.0
